#!/bin/bash
set -e
mkdir -p build-release
(
    cd build-release
    export CXX=${COMPILER:-'clang++'}
    conan install --build=missing ../
    cmake -DCMAKE_BUILD_TYPE=Release ../ -G"Unix Makefiles"
    make
)

ln -sf build-release/compile_commands.json compile_commands.json
